### ISSUE TITLE
Is sqids-kotlin maven repo daijobu?

### ISSUE THREAD

**Issue by MarcAtSP** [sqids/sqids-kotlin#7]
Is sqids-kotlin maven repo daijobu?

https://repo.maven.apache.org/maven2/org/sqids/sqids-kotlin/0.1.0/sqids-kotlin-0.1.0.pom this page shows
404 Not Found white page of nginx.

<img width="1058" alt="image" src="https://github.com/sqids/sqids-kotlin/assets/160459181/a9f730ed-7882-4cfe-a18c-0d49cd206316">

**Comment by anfanik** [comment]
Will it be fixed?
@kevinxmorales @4kimov

**Comment by 4kimov** [comment]
@kevinxmorales Do we have blockers on this one?

**Comment by kevinxmorales** [comment]
Apologies for the delay, this shouldn't be blocked. I'll be looking into this, possibly need to reach out to Sonatype

**Comment by phinner** [comment]
Still not available on maven central :pensive:

**Comment by anfanik** [comment]
Up @kevinxmorales @4kimov

**Comment by lebedynskyi** [comment]
Still does not work

**Comment by emilelm96** [comment]
Still does not work

**Comment by AlexeyGorovoy** [comment]
Same here, had to copy the code to the project - not available via gradle dependency.

**Comment by naotiki** [comment]
Hi, I noticed that version 0.1.1 is available at the following URL:
https://repo.maven.apache.org/maven2/org/sqids/sqids-kotlin/0.1.1/

However, when I try to use it in my Gradle project, I get the following error:

```
com.example.example:main: Could not resolve org.sqids:sqids-kotlin:0.1.1.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by knight7024** [comment]
Still does not work

**Comment by kevinxmorales** [comment]
Sorry for the long delay. I've been able to pull in the library on two different machines with version 0.1.1. I've updated the README with new instructions. @knight7024 @naotiki could either of you try with the new instructions and confirm it works so we can resolve?

**Comment by knight7024** [comment]
@kevinxmorales 
~Thank you for looking quickly. Regrettably, I'm still unable to import even after trying them.~
I checked again, and it works after changing my JDK version to 21. ty!

**Comment by 4kimov** [comment]
Sounds like it's working? Closing. Re-open if necessary.
